spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/translate_project?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      #ddl-auto: create-drop
    #ddl-auto:create  自动创建对应实体类的表